ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'sass', '~> 3.2.10'                                 
gem 'compass', '0.12.2'                                 
gem 'compass-sourcemaps', "~> 0.12.2.sourcemaps.57a186c"
gem 'middleman', '~>4.3.4'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.8.2'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?